name: recklamradar
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  dropdown_button2: ^2.3.9
  image_picker: ^1.0.7
  email_validator: ^2.1.17
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  firebase_storage: ^11.6.10
  cloud_firestore: ^4.15.9
  firebase_analytics: ^10.8.10
  flutter_facebook_auth: ^6.0.4
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  intl: ^0.20.0
  font_awesome_flutter: ^10.8.0
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/json/
    - assets/images/stores/
